### ISSUE TITLE
build with garble cause "./client_linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./client_linux)"

### ISSUE THREAD

**Issue by Chinalover** [lu4p/ToRat#107]
./client_linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./client_linux)

normal linux don't support GLIBC_2.25

**Comment by Chinalover** [comment]
when build with go 

go build .

when execute client,will report this error, why?.

2020/11/09 06:11:35 CheckSetup
2020/11/09 06:11:35 Elevate
2020/11/09 06:11:35 copyExecuteable
2020/11/09 06:11:35 Path for bypass: ( /root/.cache/libssh/libssh )
2020/11/09 06:11:35 Setup
2020/11/09 06:11:35 NetClient
2020/11/09 06:11:35 Could not connect: dial tcp: address 42xok2hk7ifo6wwjjq3mlynxs3cjez7a4pi77jrirvt3dc2adtst5lqd.onion: no suitable address found

**Comment by Chinalover** [comment]
when build with go

go build .

when execute client,will report this error, why?.

2020/11/09 06:11:35 CheckSetup
2020/11/09 06:11:35 Elevate
2020/11/09 06:11:35 copyExecuteable
2020/11/09 06:11:35 Path for bypass: ( /root/.cache/libssh/libssh )
2020/11/09 06:11:35 Setup
2020/11/09 06:11:35 NetClient
2020/11/09 06:11:35 Could not connect: dial tcp: address [masked].onion: no suitable address found

**Comment by lu4p** [comment]
I think this is now fixed via adding `-tags=netgo` to the build, can you test?

**Comment by lu4p** [comment]
@Chinalover  I think this is now fixed via adding -tags=netgo to the build, can you test?

**Comment by Chinalover** [comment]
don't works.
i think maybe docker image golang:last has  advanced glibc version
i can't run the binary on ubuntu 16.04 etc. (glibc 2.23)

**Comment by lu4p** [comment]
@Chinalover This is maybe fixed via adding -extflags=-static, I get some warnings, maybe it will work regardless, can you test?
I also tried linking with musl which can be statically linked, unlike glibc however musl has some other issues.

**Comment by lu4p** [comment]
Closing due to lack of info.
