### ISSUE TITLE
I fork this repo to test,have error after client connect

### ISSUE THREAD

**Issue by b3r1ch** [lu4p/ToRat#139]
## error
git clone https://github.com/b3r1ch/ToRat.git
docker build . -t torat
docker run -it -v "$(pwd)"/dist:/dist_ext torat

After I execute `docker run -it -v "$(pwd)"/dist:/dist_ext torat`, the client execution file is generated to the ./dist
I upload client_linux to my other server and exec this client file
But server print some error:
[Server] /ToRat/cmd/server$ 2020/12/11 13:49:11 [!] Rsa: crypto/rsa: decryption error
2020/12/11 13:49:11 Invalid Hostname: crypto/rsa: decryption error

**Comment by lu4p** [comment]
Can you delete the ~/.cache/libssh folder and try again?
This should probably be fixed via regenerating the hostname if it is rejected by the server.
