### ISSUE TITLE
The client shuts down when the server is disconnected

### ISSUE THREAD

**Issue by strannik-j** [lu4p/ToRat#140]
The client shuts down when the server is disconnected and must be restarted manually. This is very inconvenient, because the server may be disconnected due to an error or lose connection. The client must wait for the server to appear on the network and reconnect.

**Comment by myInstagramAlternative** [comment]
I agree, at least it would be nice once the client loses connection just crash the client and give an error as exit code (like 1 or 126, idk)

I will take a look once I learn more about Go until that happens I can't do mucho :(
(+1)

Besides this problem, I'm very impressed with this project.
@lu4p Would u implement this for money?

I can't do much, I would donate 10$ monthly as long I use this code if this idea melts into code.
Regards

**Comment by lu4p** [comment]
Usually the client should reconnect. Sometimes it doesn't, I might look into this later this week.

@myInstagramAlternative Donations are always apreciated.
