### ISSUE TITLE
Client `down` command cannot resolve paths

### ISSUE THREAD

**Issue by JustinTimperio** [lu4p/ToRat#178]
```
[vBHv3Vc5awx39ivu] /$ down /etc/fstab
[!] Download failed:open bots/vBHv3Vc5awx39ivu/etc/fstab: no such file or directory
```

**Comment by lu4p** [comment]
This is probably a permissions issue (owned by root with restricted permissions)

**Comment by JustinTimperio** [comment]
I don't think that is the case unless it's on the server-side. The error is that the folder path within `/bots` it's not created.

**Comment by JustinTimperio** [comment]
@lu4p This can be fixed with this: https://github.com/JustinTimperio/ToRat/commit/e16668ce25b44933b6e02574642d2163a6fd0014
