### ISSUE TITLE
remote error: tls: bad certificate

### ISSUE THREAD

**Issue by 2-man** [lu4p/ToRat#239]
Hello,

I have errors form clients:

Invalid hostname: remote error: tls: bad certificate
Invalid hostname: remote error: tls: bad certificate
Invalid hostname: remote error: tls: bad certificate

OS: Parrot OS 4.11.1

**Comment by lu4p** [comment]
Are you sure that you use the client and server from the same build?

**Comment by JustinTimperio** [comment]
I have observed this and other similar behavior. This can happen for a lot of reasons but I have noticed that tunnels and other VPN's can mess with the server's ability to establish a secure connection(typically just needs a `sudo docker systemctl restart`). As @lu4p suggested this could be related to the build but hypothetically builds should never colid even when multiple are running at once.

If this behavior continues please post a full debug log for both the client and server.

**Comment by 2-man** [comment]
> Are you sure that you use the client and server from the same build?

Yes, for sure



> I have observed this and other similar behavior. This can happen for a lot of reasons but I have noticed that tunnels and other VPN's can mess with the server's ability

confirmed, it was vpn

**Comment by lu4p** [comment]
Closing as I don't think we can do much about a VPN messing with packets.
