### ISSUE TITLE
The clients should reconnect automatically

### ISSUE THREAD

**Issue by Yefori** [lu4p/ToRat#253]
When the server is offline accidentally, the clients will be disconnected.
But when the server is online again, the clients will not reconnect automatically.
Will it be fixed or some functions like this will be added?

**Comment by lu4p** [comment]
I agree that they should, I think it works most of the time but sometimes not we should investigate this.

**Comment by JustinTimperio** [comment]
I have never experienced this and I am fairly confident this is a one-off. @Yefori Do you have any logs you can provide? Arch? Distro?

**Comment by Yefori** [comment]
> I have never experienced this and I am fairly confident this is a one-off. @Yefori Do you have any logs you can provide? Arch? Distro?

Sorry, but I haven't use torat for a long time. I think I can't provide more help.
