### ISSUE TITLE
Clients not showing up

### ISSUE THREAD

**Issue by alphaO4** [lu4p/ToRat#254]
Hey guys. 
I tried to set ToRat up, with the setup guide provided.
Wenn I try to connect a client by installing the Linux and windows Clients, they won't show up. 
I checked with my VPS hoster, and they dont prohibit Tor traffic so they aren't the Problem. Any Idea on what the problem might be? 
Kind Regards 
AlphaO4

**Comment by lu4p** [comment]
Are you sure that you use the most recently generated client binary?

**Comment by alphaO4** [comment]
Yes, the generation of the binary was only a few minutes away from the installation on my test-pc

**Comment by lu4p** [comment]
@alphaO4 This should be fixed by https://github.com/lu4p/ToRat/commit/e2c49f44866ff9d064fa0ad91452b04a289d6218, can you confirm?

**Comment by alphaO4** [comment]
Yes, I can thanks!

> @alphaO4 This should be fixed by https://github.com/lu4p/ToRat/commit/e2c49f44866ff9d064fa0ad91452b04a289d6218, can you confirm?
