### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by deaconxyz** [lu4p/ToRat#256]
After building a docker image I start server and it starts on port 8000 with http server tor service started as well but it stops there.
When I press any key it lets me insert commands but clients cannot connect from windows or linux environment.

Is there any way to debug or something?

**Comment by lu4p** [comment]
@deaconxyz This should be fixed by https://github.com/lu4p/ToRat/commit/e2c49f44866ff9d064fa0ad91452b04a289d6218, can you confirm?

**Comment by deaconxyz** [comment]
It works now, but mostly on linux. Sometimes when starting server there is problem loading port configuration and exiting.
I tried making client for windows without UPX and it works for the first time, but on other boot and even trying to execute it manually doesn't work.

**Comment by lu4p** [comment]
I tested windows persistence and such a long time ago there might be some changes, I'm currently not really interested in testing on windows, but doesn't the client work at all with upx?

**Comment by JustinTimperio** [comment]
@lu4p @deaconxyz Both Linux and Windows persistence doesn't work. I have a prototype for this but it's kind of messy and persistence is complex in general. 

I do have some qualms about adding it though. This is a fairly powerful payload and the ability to just make it persist without any skill on behalf of the user is questionable I think. This may result in a lot of accidentally "infected" systems

**Comment by deaconxyz** [comment]
That sounds tempting.
I can confirm that persistence is not working both on Linux and Windows.
From what I have seen there is just hkcu/hklm persistence enabled for windows and payload might have get removed while escalating or something, not sure though. I'll try to use other unused methods inside source and report back here.

I am not sure that upx is breaking payload on win, it may be some other issue happening.
Also is there a debug info where I can see which errors happened on client side as I am new in Go environment :) ?
