### ISSUE TITLE
Invalid Hostname rpc: can't find service API.Hostname

### ISSUE THREAD

**Issue by viencokhi** [lu4p/ToRat#41]
I tested but client can't connect to server but this message show up instead.
Invalid Hostname rpc: can't find service API.Hostname

**Comment by lu4p** [comment]
@viencokhi Can reproduce something broke in a recent release of garble.

**Comment by lu4p** [comment]
See https://github.com/mvdan/garble/issues/93

**Comment by lu4p** [comment]
@viencokhi Fixed it temporaily by not using `-literals` while this provides no obfuscation for literals in the binary it is better then non working builds. Keeping this open until the issue in garble is fixed.
