### ISSUE TITLE
Demo 

### ISSUE THREAD

**Issue by sparta34** [lu4p/ToRat#6]
can you make a demo for your RAt please thanks

**Comment by lu4p** [comment]
Can you give more details on what this demo should look like?

**Comment by lu4p** [comment]
Will write a detailed guide for the docker image

**Comment by sparta34** [comment]
ok thanks

**Comment by lu4p** [comment]
@sparta34 Docker Image is now up please provide feedback if you run into any issues/ have suggestions for improving the documentation

https://github.com/lu4p/ToRat/wiki/How-to-use-Docker-Image

**Comment by lu4p** [comment]
@sparta34 How is it going?

**Comment by sparta34** [comment]
working fine thanks for sharing such great tool
