### ISSUE TITLE
Invalid Hostname Unsufficent AesKey length

### ISSUE THREAD

**Issue by viencokhi** [lu4p/ToRat#67]
I just grab the latest repo code. Build success and run windows client but these message popup in server console:
```
EncHostname []
Invalid Hostname Unsufficent AesKey length
```

Linux client work fine.

**Comment by lu4p** [comment]
Will invesigate only tested the last versions on Linux.

**Comment by abenfield** [comment]
I am experiencing this with the Windows Client as well. Any updates? Thanks.

**Comment by lu4p** [comment]
@abenfield @viencokhi Should be fixed now, please let me know if it works on windows.

**Comment by abenfield** [comment]
Reviewed and can confirm that Windows Client works.

**Comment by lu4p** [comment]
Nice thanks!
